copyright: Copyright &copy; 2021 hotio<br>Logo by <a href="https://www.flaticon.com/authors/freepik">Freepik</a> from <a href="https://www.flaticon.com">flaticon.com</a> and <a href="https://freeicons.io/profile/6200">Soni Sokell</a> on <a href="https://freeicons.io">freeicons.io</a>
edit_uri: 'website/edit/master/docs'

extra:
  social:
  - icon: fontawesome/solid/heart
    link: 'https://hotio.dev/#donations'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://hotio.dev/discord'
    name: Discord
  - icon: fontawesome/brands/docker
    link: 'https://hub.docker.com/u/hotio'
    name: Docker
  - icon: fontawesome/brands/github
    link: 'https://github.com/hotio'
    name: GitHub
  - icon: fontawesome/solid/at
    link: 'mailto:input@hotio.dev'
    name: E-mail

extra_css:
  - stylesheets/extra.css

plugins:
- search
- redirects:
    redirect_maps:
      discord.md: 'https://discord.gg/3SnkuKp'
      dockerhub.md: 'https://hub.docker.com/u/hotio'
      github.md: 'https://github.com/hotio'
      ghcr.md: 'https://github.com/orgs/hotio/packages?ecosystem=container&visibility=public'
      donate.md: 'https://hotio.dev/#donations'

repo_name: hotio
repo_url: https://github.com/hotio
site_author: hotio
site_description: Documentation for all Docker images maintained by hotio.
site_name: hotio.dev
site_url: https://hotio.dev

theme:
  icon:
    repo: fontawesome/brands/github
  favicon: img/favicon.ico
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
  language: en
  logo: img/logo-header.png
  name: material
  palette:
    scheme: hotio
  custom_dir: docs/overrides

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - toc:
      permalink: true
  - admonition

google_analytics:
  - UA-126819406-1
  - auto

nav:
- Home: index.md
- Containers:
  - Tags overview: tags-overview.md
  - Custom scripts: custom-scripts.md
  - The libseccomp2 saga: libseccomp2-saga.md
  - Apps:
    - hotio/apprise: containers/apprise.md
    - hotio/autoscan: containers/autoscan.md
    - hotio/bazarr: containers/bazarr.md
    - hotio/borg: containers/borg.md
    - hotio/cloudflareddns: containers/cloudflareddns.md
    - hotio/conreq: containers/conreq.md
    - hotio/crop: containers/crop.md
    - hotio/duplicacy: containers/duplicacy.md
    - hotio/hdidle: containers/hdidle.md
    - hotio/jackett: containers/jackett.md
    - hotio/jellyfin: containers/jellyfin.md
    - hotio/lidarr: containers/lidarr.md
    - hotio/mergerfs: containers/mergerfs.md
    - hotio/movearr: containers/movearr.md
    - hotio/mylar3: containers/mylar3.md
    - hotio/nzbget: containers/nzbget.md
    - hotio/nzbhydra2: containers/nzbhydra2.md
    - hotio/ombi: containers/ombi.md
    - hotio/overseerr: containers/overseerr.md
    - hotio/plex: containers/plex.md
    - hotio/plexarr: containers/plexarr.md
    - hotio/qbittorrent: containers/qbittorrent.md
    - hotio/qflood: containers/qflood.md
    - hotio/radarr: containers/radarr.md
    - hotio/rar2fs: containers/rar2fs.md
    - hotio/rclone: containers/rclone.md
    - hotio/readarr: containers/readarr.md
    - hotio/requestrr: containers/requestrr.md
    - hotio/restic: containers/restic.md
    - hotio/rflood: containers/rflood.md
    - hotio/sabnzbd: containers/sabnzbd.md
    - hotio/scrutiny: containers/scrutiny.md
    - hotio/sonarr: containers/sonarr.md
    - hotio/stash: containers/stash.md
    - hotio/tautulli: containers/tautulli.md
    - hotio/trackarr: containers/trackarr.md
    - hotio/unpackerr: containers/unpackerr.md
  - Base Images:
    - hotio/base: containers/base.md
    - hotio/mono: containers/mono.md
- Arr Discord Notifier: arr-discord-notifier.md
- Pullio: pullio.md
